export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_MY_PRODUCTS = "GET_MY_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
